# Generated by Django 4.0.3 on 2022-03-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('email', models.EmailField(max_length=254, unique=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=255)),
                ('picture', models.URLField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
