# Generated by Django 4.0.3 on 2022-03-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='title',
        ),
    ]
