# Generated by Django 4.0.3 on 2022-03-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_name_activity_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='order',
        ),
    ]
