# Generated by Django 4.0.3 on 2022-03-25 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_todoitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='description',
        ),
    ]
