# Generated by Django 4.0.3 on 2022-03-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_created_at_profile_updated_at'),
        ('task', '0004_remove_todoitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_comment', to='profile.profile'),
        ),
        migrations.DeleteModel(
            name='Reaction',
        ),
    ]
