# Generated by Django 4.0.3 on 2022-03-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_profile_created_at_profile_updated_at'),
        ('task', '0005_comment_likes_delete_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_comments', to='profile.profile'),
        ),
    ]
