# Generated by Django 4.0.3 on 2022-04-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='due_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
